/*
 * This file is generated by jOOQ.
 */
package db.jooq.vivino;


import db.jooq.vivino.tables.Wines;


/**
 * Convenience access to all tables in vivino.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>vivino.wines</code>.
     */
    public static final Wines WINES = Wines.WINES;
}
