/*
 * This file is generated by jOOQ.
 */
package db.jooq.vivino;


import db.jooq.vivino.tables.Wines;
import org.jooq.Catalog;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;

import java.util.Arrays;
import java.util.List;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Vivino extends SchemaImpl {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>vivino</code>
     */
    public static final Vivino VIVINO = new Vivino();

    /**
     * The table <code>vivino.wines</code>.
     */
    public final Wines WINES = Wines.WINES;

    /**
     * No further instances allowed
     */
    private Vivino() {
        super("vivino", null);
    }


    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Table<?>> getTables() {
        return Arrays.asList(
            Wines.WINES
        );
    }
}
